declare const GM_addStyle: Function
declare const GM_deleteValue: Function
declare const GM_addValueChangeListener: Function
declare const GM_removeValueChangeListener: Function
declare const GM_setValue: Function
declare const GM_getValue: Function
declare const GM_log: Function
declare const GM_getResourceText: Function
declare const GM_getResourceURL: Function
declare const GM_registerMenuCommand: Function
declare const GM_unregisterMenuCommand: Function
declare const GM_openInTab: Function
declare const GM_xmlhttpRequest: Function
declare const GM_download: Function
declare const GM_getTab: Function
declare const GM_saveTab: Function
declare const GM_getTabs: Function
declare const GM_notification: Function
declare const GM_setClipboard: Function
declare const GM_info: Function
declare const GM_listValues: Function
